project:
  type: book

book:
  title: "Malnutrition"
  author: "Jesús David Zamora Thowinsson"
  date: "8/15/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - Analisis_EDA.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    code-fold: show
    theme:
      - superhero
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

