# Nombre del flujo de trabajo
name: Deploy Quarto Website to GitHub Pages

# Se ejecuta cada vez que haces 'git push' a la rama 'master'
on:
  push:
    branches: [ master ]

# Permisos necesarios
permissions:
  contents: write
  pages: write
  id-token: write

# Define el trabajo a realizar
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.2'

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v2

      # --- AQUÍ AÑADIMOS EL NUEVO PAQUETE ---
      - name: Install R Packages
        run: |
          install.packages(c("readxl", "tidyverse", "knitr", "kableExtra"))
        shell: Rscript {0}
      # ----------------------------------------

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}